version: '3'
services:
  omr_scanner:
    image: mythrex/omr_scanner
    container_name: omr_scanner
    environment:
      - DEBUG=TRUE
    ports:
      - 3000:3000
      - 35729:35729
    volumes:
      - .:/usr/src/app
